clang-tidy: Add override keywords
Marked virtual functions with the `override` keyword to ensure
they correctly override base class functions. This resolves
-Winconsistent-missing-override warnings and improves code safety
and readability by explicitly indicating overridden functions.

'''
item_updater.hpp:120:18: [0m[0;1;31m
  error: [0m[1m'deleteAll' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override
static/item_updater_static.hpp:75:10: [0m[0;1;31m
   error: [0m[1m'validateImage' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override][0m
'''

Tested: Build verified

Change-Id: Iee2bb85498db72c8f2a9f265e0490fff9288f5f4
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>