mmc: clang-tidy: Add override keyword
Marked virtual functions with the `override` keyword to ensure
they correctly override base class functions. This resolves
-Winconsistent-missing-override warnings and improves code safety
and readability by explicitly indicating overridden functions.

```
Error while processing /var/jenkins-openbmc/workspace/ci-repository/openbmc/openpower-pnor-code-mgmt/mmc/item_updater_mmc.hpp.
/var/jenkins-openbmc/workspace/ci-repository/openbmc/openpower-pnor-code-mgmt/mmc/item_updater_mmc.hpp:94:10: error: 'validateImage' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
   94 |     bool validateImage(const std::string& path);
      |          ^
../item_updater.hpp:199:18: note: overridden virtual function is here
  199 |     virtual bool validateImage(const std::string& path) = 0;
      |                  ^
```

Tested: CI runs with no errors.

Change-Id: I24e5cae09e2cdeacf0155d5de70a6ecbae5e00e0
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>